### ISSUE TITLE
Full protein vs list of residues

### ISSUE THREAD

**Issue by Leroy-r** [Moutoussamy/PeriProt#1]
Hello! 

Thank you for sharing this tool! The documentation is very clear which is very useful for non-bioinformatician (like me).

Periprot analyze the interaction for the full protein, is it possible to restraint the analysis to only some residues? This could make the calculation faster since I am not interested in all residues.

Best,
Roland

**Comment by Moutoussamy** [comment]
Hi!

It should not be too complicated to do (at least for H-bond, hydrophobic contact and cation-pi interaction), I will do it in the next days :) 

Emmanuel

**Comment by Moutoussamy** [comment]
I am working on it now !

**Comment by Moutoussamy** [comment]
it should work now, let me know if it is ok for you.

**Comment by Leroy-r** [comment]
Yes, it works. Thank you for the time you spent on it.

**Comment by Moutoussamy** [comment]
OK, let me know if you need something else ! :)
